"""Renamed vul attribute

Revision ID: 31122b500acf
Revises: 86596fa82189
Create Date: 2025-01-02 21:37:46.884016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31122b500acf'
down_revision = '86596fa82189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('references', sa.Text(), nullable=True))
        batch_op.drop_column('references_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('references_list', mysql.TEXT(), nullable=True))
        batch_op.drop_column('references')

    # ### end Alembic commands ###
