"""Rename references to references_list

Revision ID: 86596fa82189
Revises: 99945816da40
Create Date: 2024-12-26 23:58:38.082084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86596fa82189'
down_revision = '99945816da40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('references_list', sa.Text(), nullable=True))
        batch_op.drop_column('references')
        batch_op.drop_column('screenshot_thumb_path')
        batch_op.drop_column('screenshot_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screenshot_path', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('screenshot_thumb_path', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('references', mysql.TEXT(), nullable=True))
        batch_op.drop_column('references_list')

    # ### end Alembic commands ###
